# Generated by Django 4.1.4 on 2023-01-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_admin_user_email_user_is_active_user_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
