# Generated by Django 4.1.4 on 2023-01-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.png', upload_to='category_image'),
        ),
    ]
