# Generated by Django 4.1.4 on 2023-01-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_images',
            field=models.FileField(default='none.jpg', upload_to='related_images'),
        ),
    ]
